// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TfsForms.Data;

#nullable disable

namespace TfsForms.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260210141342_seed crims")]
    partial class seedcrims
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TfsForms.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("CRIMSReportingEntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("GoAMLReportingEntityId")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RapidAMLReportingEntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TempREId")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("TempREId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TfsForms.Models.ArchivetblResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountHolderName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("AccountType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("AmountFrozen")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BVN")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("ComplianceSteps")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal?>("CurrentBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DateFrozen")
                        .HasColumnType("datetime2");

                    b.Property<int>("DesigneeId")
                        .HasColumnType("int");

                    b.Property<bool>("HasRelationship")
                        .HasColumnType("bit");

                    b.Property<string>("ImplementationObservations")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsAccountFrozen")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFalsePositive")
                        .HasColumnType("bit");

                    b.Property<string>("LegalChallenges")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ReportingEntityCategory")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ReportingEntityName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SuspiciousActivity")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DesigneeId");

                    b.ToTable("ArchivetblResponses");
                });

            modelBuilder.Entity("TfsForms.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArchivetblResponseId")
                        .HasColumnType("int");

                    b.Property<string>("AssetType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int?>("DesigneeId")
                        .HasColumnType("int");

                    b.Property<decimal>("EstimatedValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ResponseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArchivetblResponseId");

                    b.HasIndex("DesigneeId");

                    b.HasIndex("ResponseId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("TfsForms.Models.Associate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("AdditionalIdentifiers")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ArchivetblResponseId")
                        .HasColumnType("int");

                    b.Property<string>("AssociateName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("DesigneeId")
                        .HasColumnType("int");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ResponseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber");

                    b.HasIndex("ArchivetblResponseId");

                    b.HasIndex("DesigneeId");

                    b.HasIndex("ResponseId");

                    b.ToTable("Associates");
                });

            modelBuilder.Entity("TfsForms.Models.Designee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDesignated")
                        .HasColumnType("datetime2");

                    b.Property<string>("DesignationType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NslPermanentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OriginatingLea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RcNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Designees");
                });

            modelBuilder.Entity("TfsForms.Models.FalsePositive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("AdditionalIdentifiers")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ArchivetblResponseId")
                        .HasColumnType("int");

                    b.Property<string>("BVN")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int?>("DesigneeId")
                        .HasColumnType("int");

                    b.Property<string>("MatchedName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ResponseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber");

                    b.HasIndex("ArchivetblResponseId");

                    b.HasIndex("DesigneeId");

                    b.HasIndex("ResponseId");

                    b.ToTable("FalsePositives");
                });

            modelBuilder.Entity("TfsForms.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("TfsForms.Models.Response", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DesigneeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("ReportingEntityId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DesigneeId");

                    b.HasIndex("QuestionId", "DesigneeId", "ReportingEntityId")
                        .IsUnique();

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("TfsForms.Models.lkCRIMSLEA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CRIMSDomain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LEA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("lkCRIMSLEAs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CRIMSDomain = "army.mil.ng",
                            LEA = "6 Military Intelligence Brigade"
                        },
                        new
                        {
                            Id = 2,
                            CRIMSDomain = "abiairs.com",
                            LEA = "Abia State Internal Revenue Service"
                        },
                        new
                        {
                            Id = 3,
                            CRIMSDomain = "adamawabir.org",
                            LEA = "Adamawa State Board Of Internal Revenue"
                        },
                        new
                        {
                            Id = 4,
                            CRIMSDomain = "akirs.ak.gov.ng",
                            LEA = "Akwa Ibom State Internal Revenue Service"
                        },
                        new
                        {
                            Id = 5,
                            CRIMSDomain = "airs.an.gov.ng",
                            LEA = "Anambra State Internal Revenue Service"
                        },
                        new
                        {
                            Id = 6,
                            CRIMSDomain = "armu.gov.ng",
                            LEA = "Asset Recovery Mgt Unit"
                        },
                        new
                        {
                            Id = 7,
                            CRIMSDomain = "birs.bu.gov.ng",
                            LEA = "Bauchi State Internal Revenue Service"
                        },
                        new
                        {
                            Id = 8,
                            CRIMSDomain = "bir.by.gov.ng",
                            LEA = "Bayelsa State Board Of Internal Revenue"
                        },
                        new
                        {
                            Id = 9,
                            CRIMSDomain = "birs.be.gov.ng",
                            LEA = "Benue State Internal Revenue Service"
                        },
                        new
                        {
                            Id = 10,
                            CRIMSDomain = "cbn.gov.ng",
                            LEA = "Central Bank of Nigeria"
                        },
                        new
                        {
                            Id = 11,
                            CRIMSDomain = "china.foreign.mission",
                            LEA = "China Foreign Mission"
                        },
                        new
                        {
                            Id = 12,
                            CRIMSDomain = "ccb.gov.ng",
                            LEA = "Code of Conduct Bureau (CCB)"
                        },
                        new
                        {
                            Id = 13,
                            CRIMSDomain = "ccg.gov.ng",
                            LEA = "Complex Cases Group"
                        },
                        new
                        {
                            Id = 14,
                            CRIMSDomain = "cpc.gov.ng",
                            LEA = "Consumer Protection Council"
                        },
                        new
                        {
                            Id = 15,
                            CRIMSDomain = "cac.gov.ng",
                            LEA = "Corporate Affairs Commissions"
                        },
                        new
                        {
                            Id = 16,
                            CRIMSDomain = "crirs.ng",
                            LEA = "Cross River Internal Revenue Service"
                        },
                        new
                        {
                            Id = 17,
                            CRIMSDomain = "nafic.gov.ng",
                            LEA = "DEACTIVATED-NAF Intel Corp"
                        },
                        new
                        {
                            Id = 18,
                            CRIMSDomain = "dia.gov.ng",
                            LEA = "Defence Intelligence Agency"
                        },
                        new
                        {
                            Id = 19,
                            CRIMSDomain = "deltabir.com",
                            LEA = "Delta State Internal Revenue Service"
                        },
                        new
                        {
                            Id = 20,
                            CRIMSDomain = "dss.gov.ng",
                            LEA = "Department of State Service (DSS)"
                        },
                        new
                        {
                            Id = 21,
                            CRIMSDomain = "dmi.gov.ng",
                            LEA = "Directorate of Military Intelligence"
                        },
                        new
                        {
                            Id = 22,
                            CRIMSDomain = "efcc.gov.ng",
                            LEA = "Economic and Financial Crimes Commission (EFCC)"
                        },
                        new
                        {
                            Id = 23,
                            CRIMSDomain = "eirs.gov.ng",
                            LEA = "Edo State IRS"
                        },
                        new
                        {
                            Id = 24,
                            CRIMSDomain = "ekirs.gov.ng",
                            LEA = "Ekiti State Internal Revenue Service"
                        },
                        new
                        {
                            Id = 25,
                            CRIMSDomain = "enugustate.gov.ng",
                            LEA = "Enugu State Internal Revenue Service"
                        },
                        new
                        {
                            Id = 26,
                            CRIMSDomain = "fctirs.gov.ng",
                            LEA = "FCT-IRS"
                        },
                        new
                        {
                            Id = 27,
                            CRIMSDomain = "fccpc.gov.ng",
                            LEA = "Federal Competition and Consumer Protection Commission"
                        },
                        new
                        {
                            Id = 28,
                            CRIMSDomain = "firs.gov.ng",
                            LEA = "Federal Inland Revenue Service"
                        },
                        new
                        {
                            Id = 29,
                            CRIMSDomain = "fmoj.gov.ng",
                            LEA = "Federal Ministry of Justice"
                        },
                        new
                        {
                            Id = 30,
                            CRIMSDomain = "frsc.gov.ng",
                            LEA = "Federal Road Safety Corp"
                        },
                        new
                        {
                            Id = 31,
                            CRIMSDomain = "fciid.gov.ng",
                            LEA = "Force Criminal Investigation and Intelligence Bureau"
                        },
                        new
                        {
                            Id = 32,
                            CRIMSDomain = "gombe.igr.ng",
                            LEA = "Gombe State Internal Revenue Service"
                        },
                        new
                        {
                            Id = 33,
                            CRIMSDomain = "iirs.im.gov.ng",
                            LEA = "Imo State Internal Revenue Service"
                        },
                        new
                        {
                            Id = 34,
                            CRIMSDomain = "icpc.gov.ng",
                            LEA = "Independent Corrupt Practices and Other Related Offences Commission (ICPC)"
                        },
                        new
                        {
                            Id = 35,
                            CRIMSDomain = "intlcoop.gov.ng",
                            LEA = "International Cooperation Department(Federal Ministry of Justice)"
                        },
                        new
                        {
                            Id = 36,
                            CRIMSDomain = "interpol.com",
                            LEA = "INTERPOL"
                        },
                        new
                        {
                            Id = 37,
                            CRIMSDomain = "investigate.nfiu.gov.ng",
                            LEA = "Investigate"
                        },
                        new
                        {
                            Id = 38,
                            CRIMSDomain = "jic.gov.ng",
                            LEA = "Joint Investigation Center"
                        },
                        new
                        {
                            Id = 39,
                            CRIMSDomain = "kadirs.gov.ng",
                            LEA = "Kaduna State Internal Revenue Service"
                        },
                        new
                        {
                            Id = 40,
                            CRIMSDomain = "kirs.gov.ng",
                            LEA = "Kano State Internal Revenue Service"
                        },
                        new
                        {
                            Id = 41,
                            CRIMSDomain = "irs.kt.gov.ng",
                            LEA = "Katsina State Internal Revenue Service"
                        },
                        new
                        {
                            Id = 42,
                            CRIMSDomain = "irs.kg.gov.ng",
                            LEA = "Kogi State Internal Revenue Service"
                        },
                        new
                        {
                            Id = 43,
                            CRIMSDomain = "lirs.gov.ng",
                            LEA = "Lagos State Internal Revenue Service"
                        },
                        new
                        {
                            Id = 44,
                            CRIMSDomain = "mof.gov.ng",
                            LEA = "Ministry of Finance"
                        },
                        new
                        {
                            Id = 45,
                            CRIMSDomain = "irs.na.gov.ng",
                            LEA = "Nasarawa State Internal Revenue Service"
                        },
                        new
                        {
                            Id = 46,
                            CRIMSDomain = "nafdac.gov.ng",
                            LEA = "National Agency for Food and Drug Administration"
                        },
                        new
                        {
                            Id = 47,
                            CRIMSDomain = "naptip.gov.ng",
                            LEA = "National Agency for the Prohibition of Trafficking in Persons"
                        },
                        new
                        {
                            Id = 48,
                            CRIMSDomain = "ctc.gov.ng",
                            LEA = "National Counter Terrorism Centre"
                        },
                        new
                        {
                            Id = 49,
                            CRIMSDomain = "nccc.gov.ng",
                            LEA = "National Cybersecurity Coordination Centre (NCCC)"
                        },
                        new
                        {
                            Id = 50,
                            CRIMSDomain = "defencecollege@ndc.gov.ng",
                            LEA = "National Defence College Nigeria"
                        },
                        new
                        {
                            Id = 51,
                            CRIMSDomain = "ndlea.gov.ng",
                            LEA = "National Drug Law Enforcement Agency"
                        },
                        new
                        {
                            Id = 52,
                            CRIMSDomain = "nesrea.gov.ng",
                            LEA = "National Environmental Standards and Regulations Enforcement Agency"
                        },
                        new
                        {
                            Id = 53,
                            CRIMSDomain = "nimc.gov.ng",
                            LEA = "National Identity Management Commission"
                        },
                        new
                        {
                            Id = 54,
                            CRIMSDomain = "naicom.gov.ng",
                            LEA = "National Insurance Commission"
                        },
                        new
                        {
                            Id = 55,
                            CRIMSDomain = "nia.gov.ng",
                            LEA = "National Intelligence Agency"
                        },
                        new
                        {
                            Id = 56,
                            CRIMSDomain = "nlrc.gov.ng",
                            LEA = "National Lottery Regulatory Commission"
                        },
                        new
                        {
                            Id = 57,
                            CRIMSDomain = "navalic.gov.ng",
                            LEA = "NAVAL Intel Corp"
                        },
                        new
                        {
                            Id = 58,
                            CRIMSDomain = "ngsirs.gov.ng",
                            LEA = "Niger State Internal Revenue Service"
                        },
                        new
                        {
                            Id = 59,
                            CRIMSDomain = "nah.gov.ng",
                            LEA = "Nigeria Army Head Quarters"
                        },
                        new
                        {
                            Id = 60,
                            CRIMSDomain = "ncopyc.gov.ng",
                            LEA = "Nigeria Copyright Commission"
                        },
                        new
                        {
                            Id = 61,
                            CRIMSDomain = "nps.gov.ng",
                            LEA = "Nigeria Correctional Service"
                        },
                        new
                        {
                            Id = 62,
                            CRIMSDomain = "ncs.gov.ng",
                            LEA = "Nigeria Customs Service"
                        },
                        new
                        {
                            Id = 63,
                            CRIMSDomain = "ndic.gov.ng",
                            LEA = "Nigeria Deposit Insurance Corporation"
                        },
                        new
                        {
                            Id = 64,
                            CRIMSDomain = "neiti.gov.ng",
                            LEA = "Nigeria Extractive Industries Transparency Initiative"
                        },
                        new
                        {
                            Id = 65,
                            CRIMSDomain = "nis.gov.ng",
                            LEA = "Nigeria Immigration Service"
                        },
                        new
                        {
                            Id = 66,
                            CRIMSDomain = "npf.gov.ng",
                            LEA = "Nigeria Police Force (NPF)"
                        },
                        new
                        {
                            Id = 67,
                            CRIMSDomain = "npfamlcft.gov.ng",
                            LEA = "Nigeria Police Force Anti-Money Laundering and Countering the Financing of Terrorism Section"
                        },
                        new
                        {
                            Id = 68,
                            CRIMSDomain = "npfdo.gov.ng",
                            LEA = "Nigeria Police Force Department of Operations (FCT Police Command)"
                        },
                        new
                        {
                            Id = 69,
                            CRIMSDomain = "npfigpmu.gov.ng",
                            LEA = "Nigeria Police Force IGP Monitoring Unit (NPF-IGPMU)"
                        },
                        new
                        {
                            Id = 70,
                            CRIMSDomain = "npfirt.gov.ng",
                            LEA = "Nigeria Police Force Intelligence Response Team (NPF-IRT)"
                        },
                        new
                        {
                            Id = 71,
                            CRIMSDomain = "npflagoscom.gov.ng",
                            LEA = "Nigeria Police Force Lagos Command"
                        },
                        new
                        {
                            Id = 72,
                            CRIMSDomain = "psfu.gov.ng",
                            LEA = "Nigeria Police Force, Police Special Fraud Unit (PSFU)"
                        },
                        new
                        {
                            Id = 73,
                            CRIMSDomain = "nscdc.gov.ng",
                            LEA = "Nigeria Security and Civil Defence Corps"
                        },
                        new
                        {
                            Id = 74,
                            CRIMSDomain = "naf.gov.ng",
                            LEA = "Nigerian Air Force Intel Corp"
                        },
                        new
                        {
                            Id = 75,
                            CRIMSDomain = "nacmp.gov.ng",
                            LEA = "Nigerian Army Corps of Military Police"
                        },
                        new
                        {
                            Id = 76,
                            CRIMSDomain = "naic.gov.ng",
                            LEA = "Nigerian Army Intelligence Corp"
                        },
                        new
                        {
                            Id = 77,
                            CRIMSDomain = "opudokajtfse.gov.ng",
                            LEA = "Nigerian Army OP UDO-KA (JTF-SE)"
                        },
                        new
                        {
                            Id = 78,
                            CRIMSDomain = "ncc.gov.ng",
                            LEA = "Nigerian Communication Commission"
                        },
                        new
                        {
                            Id = 79,
                            CRIMSDomain = "crims.nfiu.gov.ng",
                            LEA = "Nigerian Financial Intelligence Unit"
                        },
                        new
                        {
                            Id = 80,
                            CRIMSDomain = "navy.gov.ng",
                            LEA = "Nigerian Navy"
                        },
                        new
                        {
                            Id = 81,
                            CRIMSDomain = "npfnccc.gov.ng",
                            LEA = "NPF National Cybercrime Center (NPF-NCCC)"
                        },
                        new
                        {
                            Id = 82,
                            CRIMSDomain = "onsa.gov.ng",
                            LEA = "Office of the National Security Adviser"
                        },
                        new
                        {
                            Id = 83,
                            CRIMSDomain = "ogirs.com",
                            LEA = "Ogun State Internal Revenue Service"
                        },
                        new
                        {
                            Id = 84,
                            CRIMSDomain = "odirs.ng",
                            LEA = "ONDO STATE INTERNAL REVENUE SERVICE"
                        },
                        new
                        {
                            Id = 85,
                            CRIMSDomain = "oirs.ng",
                            LEA = "OSUN INTERNAL REVENUE SERVICE"
                        },
                        new
                        {
                            Id = 86,
                            CRIMSDomain = "psirs.gov.ng",
                            LEA = "Plateau State Internal Revenue Service"
                        },
                        new
                        {
                            Id = 87,
                            CRIMSDomain = "sector1.na.gov.ng",
                            LEA = "Sector 1: Theatre Command Nigeria Army"
                        },
                        new
                        {
                            Id = 88,
                            CRIMSDomain = "sector2.na.gov.ng",
                            LEA = "Sector 2: Theatre Command Nigeria Army"
                        },
                        new
                        {
                            Id = 89,
                            CRIMSDomain = "sector3.na.gov.ng",
                            LEA = "Sector 3: Theatre Command Nigeria Army"
                        },
                        new
                        {
                            Id = 90,
                            CRIMSDomain = "sec.gov.ng",
                            LEA = "Securities and Exchange Commission"
                        },
                        new
                        {
                            Id = 91,
                            CRIMSDomain = "scuml.gov.ng",
                            LEA = "Special Control Unit on Money Laundering (SCUML)"
                        },
                        new
                        {
                            Id = 92,
                            CRIMSDomain = "sfu.gov.ng",
                            LEA = "Special Fraud Unit"
                        },
                        new
                        {
                            Id = 93,
                            CRIMSDomain = "spip.gov.ng",
                            LEA = "Special Presidential Investigation Panel"
                        },
                        new
                        {
                            Id = 94,
                            CRIMSDomain = "son.gov.ng",
                            LEA = "Standard Organization of Nigeria"
                        },
                        new
                        {
                            Id = 95,
                            CRIMSDomain = "tarababir.gov.ng",
                            LEA = "Taraba State Internal Revenue Service"
                        },
                        new
                        {
                            Id = 96,
                            CRIMSDomain = "test.org",
                            LEA = "Test Organisation"
                        },
                        new
                        {
                            Id = 97,
                            CRIMSDomain = "voars.gov.ng",
                            LEA = "Voluntary Offshore Assets Regularization Scheme of Nigeria"
                        },
                        new
                        {
                            Id = 98,
                            CRIMSDomain = "irs.zm.gov.ng",
                            LEA = "Zamfara State Internal Revenue Service"
                        });
                });

            modelBuilder.Entity("TfsForms.Models.lkGoAMLRE", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GoAMLId")
                        .HasColumnType("int");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("lkGoAMLREs");
                });

            modelBuilder.Entity("TfsForms.Models.lkRapidAMLRE", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RapidAMLId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("lkRapidAMLREs");
                });

            modelBuilder.Entity("TfsForms.Models.tblTempRE", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("REName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("tblTempREs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            REName = "Access Bank"
                        },
                        new
                        {
                            Id = 2,
                            REName = "GT Bank"
                        },
                        new
                        {
                            Id = 3,
                            REName = "Standard Chartered Bank"
                        },
                        new
                        {
                            Id = 4,
                            REName = "Zenith Bank"
                        },
                        new
                        {
                            Id = 5,
                            REName = "Opay Digital Services"
                        },
                        new
                        {
                            Id = 6,
                            REName = "Palmpay Limited"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TfsForms.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TfsForms.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TfsForms.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TfsForms.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TfsForms.Models.ApplicationUser", b =>
                {
                    b.HasOne("TfsForms.Models.tblTempRE", "TempRE")
                        .WithMany()
                        .HasForeignKey("TempREId");

                    b.Navigation("TempRE");
                });

            modelBuilder.Entity("TfsForms.Models.ArchivetblResponse", b =>
                {
                    b.HasOne("TfsForms.Models.Designee", "Designee")
                        .WithMany()
                        .HasForeignKey("DesigneeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Designee");
                });

            modelBuilder.Entity("TfsForms.Models.Asset", b =>
                {
                    b.HasOne("TfsForms.Models.ArchivetblResponse", null)
                        .WithMany("Assets")
                        .HasForeignKey("ArchivetblResponseId");

                    b.HasOne("TfsForms.Models.Designee", null)
                        .WithMany("Assets")
                        .HasForeignKey("DesigneeId");

                    b.HasOne("TfsForms.Models.Response", "Response")
                        .WithMany()
                        .HasForeignKey("ResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Response");
                });

            modelBuilder.Entity("TfsForms.Models.Associate", b =>
                {
                    b.HasOne("TfsForms.Models.ArchivetblResponse", null)
                        .WithMany("Associates")
                        .HasForeignKey("ArchivetblResponseId");

                    b.HasOne("TfsForms.Models.Designee", null)
                        .WithMany("Associates")
                        .HasForeignKey("DesigneeId");

                    b.HasOne("TfsForms.Models.Response", "Response")
                        .WithMany()
                        .HasForeignKey("ResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Response");
                });

            modelBuilder.Entity("TfsForms.Models.FalsePositive", b =>
                {
                    b.HasOne("TfsForms.Models.ArchivetblResponse", null)
                        .WithMany("FalsePositives")
                        .HasForeignKey("ArchivetblResponseId");

                    b.HasOne("TfsForms.Models.Designee", null)
                        .WithMany("FalsePositives")
                        .HasForeignKey("DesigneeId");

                    b.HasOne("TfsForms.Models.Response", "Response")
                        .WithMany("FalsePositives")
                        .HasForeignKey("ResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Response");
                });

            modelBuilder.Entity("TfsForms.Models.Response", b =>
                {
                    b.HasOne("TfsForms.Models.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("TfsForms.Models.Designee", "Designee")
                        .WithMany("Responses")
                        .HasForeignKey("DesigneeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TfsForms.Models.Question", "Question")
                        .WithMany("Responses")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Designee");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("TfsForms.Models.ArchivetblResponse", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Associates");

                    b.Navigation("FalsePositives");
                });

            modelBuilder.Entity("TfsForms.Models.Designee", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Associates");

                    b.Navigation("FalsePositives");

                    b.Navigation("Responses");
                });

            modelBuilder.Entity("TfsForms.Models.Question", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("TfsForms.Models.Response", b =>
                {
                    b.Navigation("FalsePositives");
                });
#pragma warning restore 612, 618
        }
    }
}
